version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myusername
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

  rest_api:
    image: openjdk:17-jdk
    container_name: rest_api_container
    ports:
      - "80:8080"
    volumes:
      - ./target:/target
    depends_on:
      - mysql
    command: [ "java", "-jar", "/target/backend-0.0.1-snapshot.jar" ]